using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Security.Cryptography;
using Jellyfin.Data;
using Jellyfin.Data.Enums;
using MediaBrowser.Controller.Dto;
using MediaBrowser.Controller.Entities;
using MediaBrowser.Controller.Library;
using MediaBrowser.Model.Dto;
using MediaBrowser.Model.Entities;
using MediaBrowser.Model.Querying;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.StaticFiles;
using Jellyfin.Plugin.JellyfinEnhanced.Configuration;
using MediaBrowser.Controller;
using Jellyfin.Plugin.JellyfinEnhanced.Helpers;
using Jellyfin.Plugin.JellyfinEnhanced.Model.Jellyseerr;
using Jellyfin.Plugin.JellyfinEnhanced.Helpers.Jellyseerr;
using MediaBrowser.Model.Plugins;
using MediaBrowser.Model;
using MediaBrowser.Controller.Persistence;
using Jellyfin.Plugin.JellyfinEnhanced.Model.Arr;
using Jellyfin.Plugin.JellyfinEnhanced.Extensions;
using Jellyfin.Database.Implementations;
using Jellyfin.Database.Implementations.Enums;
using Microsoft.EntityFrameworkCore;
using Jellyfin.Plugin.JellyfinEnhanced.Services.Jellyseerr;
using Jellyfin.Plugin.JellyfinEnhanced.Services;
using Microsoft.Extensions.Logging;

namespace Jellyfin.Plugin.JellyfinEnhanced.Controllers
{
    /// <summary>
    /// Plugin config and asset endpoints (public/private config, script/css/version/locales serving).
    /// Split out of the former JellyfinEnhancedController; method bodies, routes
    /// and attributes are unchanged.
    /// </summary>
    [Route("JellyfinEnhanced")]
    [ApiController]
    public class ConfigController : JellyfinEnhancedControllerBase
    {
        public ConfigController(
            IHttpClientFactory httpClientFactory,
            ILogger<ConfigController> logger,
            IUserManager userManager,
            ISeerrCache seerrCache,
            IPluginConfigProvider configProvider)
            : base(httpClientFactory, logger, userManager, seerrCache, configProvider)
        {
        }

        [HttpGet("script")]
        public ActionResult GetMainScript() => GetScriptResource("js/plugin.js");
        [HttpGet("js/{**path}")]
        public ActionResult GetScript(string path) => GetScriptResource($"js/{path}");
        // Production bundle (dist/je.bundle.js + sourcemap), generated by the csproj
        // BuildClientBundle target and embedded from dist\**. Served with the same
        // versioned-URL immutable caching as the individual js/ files; plugin.js
        // (the loader) probes this route and falls back to per-file loading when
        // the bundle is absent or DevMode is on.
        [HttpGet("dist/{**path}")]
        public ActionResult GetBundleResource(string path) => GetScriptResource($"dist/{path}");
        // Config-page stylesheet lives in Configuration/ next to configPage.html.
        [HttpGet("Configuration/configPage.css")]
        public ActionResult GetConfigPageStylesheet() => GetScriptResource("Configuration/configPage.css");
        // Config-page script, externalized from the former inline <script> in configPage.html.
        // Loaded by the small bootstrap that remains inline there (see that file for why).
        [HttpGet("Configuration/config-page.js")]
        public ActionResult GetConfigPageScript() => GetScriptResource("Configuration/config-page.js");
        // [AllowAnonymous]: version is loaded by translations.js cache-buster pre-login.
        // Information disclosure of the plugin version is acceptable — Jellyfin core
        // exposes its own version pre-auth too. CVEs against JE are tracked publicly
        // so attackers do not need this endpoint to fingerprint a vulnerable version.
        [HttpGet("version")]
        public ActionResult GetVersion() => Content(JellyfinEnhanced.Instance?.Version.ToString() ?? "unknown");

        // Same-version development builds still need a new immutable asset URL.
        // ScriptCacheKey includes the DLL write timestamp used by the main loader.
        [HttpGet("cache-key")]
        public ActionResult GetCacheKey()
        {
            var instance = JellyfinEnhanced.Instance;
            return instance == null ? StatusCode(503) : Content(instance.ScriptCacheKey);
        }

        [HttpGet("private-config")]
        [Authorize]
        public ActionResult GetPrivateConfig()
        {
            var config = _configProvider.ConfigurationOrNull;
            if (config == null)
            {
                return StatusCode(503);
            }

            // Non-admin users receive an empty config object rather than a 403 so that the
            // client-side plugin initialises without error but never sees sensitive fields.
            if (!IsAdminUser())
            {
                return new JsonResult(new { });
            }

            // Check + log corruption so admins who never hit one of the action endpoints
            // still see a server-side error entry on private-config load.
            WarnIfArrInstancesCorrupt(config);

            return new JsonResult(BuildPrivateConfigPayload(config));
        }

        /// <summary>
        /// Pure projection of <see cref="PluginConfiguration"/> to the private-config payload
        /// (admin-only), driven by the <see cref="SettingDescriptors"/> registry. The registry
        /// is a WHITELIST — a setting without a Private descriptor never reaches the client.
        /// The exact payload (key set AND values) is pinned by the golden snapshots in
        /// JellyfinEnhanced.Tests/Snapshots.
        /// </summary>
        internal static object BuildPrivateConfigPayload(PluginConfiguration config)
            => SettingDescriptors.BuildPayload(
                SettingExposure.Private,
                new SettingContext(config, IsAuthenticated: true));

        // [AllowAnonymous]: public-config is loaded by `loadLoginImageEarly` before
        // the user logs in, so we cannot gate the whole endpoint on [Authorize].
        // Instead, sensitive Seerr fields (BaseUrl, UrlMappings) are REDACTED for
        // unauthenticated callers — they only need login-screen toggles like
        // EnableLoginImage. Authenticated callers (any Jellyfin user) get the full
        // payload so client-side "Open in Seerr" deep links still work.
        [HttpGet("public-config")]
        public ActionResult GetPublicConfig()
        {
            var config = _configProvider.ConfigurationOrNull;
            if (config == null)
            {
                return StatusCode(503);
            }

            // Only authenticated callers see internal Seerr URLs — they're used by
            // client-side deep links and would otherwise leak network topology to
            // unauthenticated visitors hitting the login page.
            bool isAuthed = User?.Identity?.IsAuthenticated == true;

            return new JsonResult(BuildPublicConfigPayload(config, isAuthed));
        }

        /// <summary>
        /// Pure projection of <see cref="PluginConfiguration"/> to the public-config payload,
        /// driven by the <see cref="SettingDescriptors"/> registry. The registry is a WHITELIST —
        /// a setting without a Public descriptor never reaches the client — and caller-dependent
        /// redaction (Seerr URLs hidden pre-login) lives in the descriptors' value accessors.
        /// The exact payload (key set AND values) is pinned by the golden snapshots in
        /// JellyfinEnhanced.Tests/Snapshots.
        /// </summary>
        internal static object BuildPublicConfigPayload(PluginConfiguration config, bool isAuthed)
            => SettingDescriptors.BuildPayload(
                SettingExposure.Public,
                new SettingContext(config, isAuthed));

        [HttpGet("locales")]
        [Authorize]
        [ResponseCache(Duration = 86400)]
        public ActionResult GetAvailableLocales()
        {
            var prefix = "Jellyfin.Plugin.JellyfinEnhanced.js.locales.";
            var suffix = ".json";
            var locales = Assembly.GetExecutingAssembly()
                .GetManifestResourceNames()
                .Where(n => n.StartsWith(prefix, StringComparison.Ordinal) && n.EndsWith(suffix, StringComparison.Ordinal))
                .Select(n => n.Substring(prefix.Length, n.Length - prefix.Length - suffix.Length))
                .Where(code => code != "en") // Exclude base English (en-GB and en-US are the usable variants)
                .OrderBy(code => code, StringComparer.OrdinalIgnoreCase)
                .ToArray();

            return Ok(locales);
        }

        [HttpGet("locales/{lang}.json")]
        public ActionResult GetLocale(string lang)
        {
            var sanitizedLang = Path.GetFileName(lang); // Basic sanitization
            var resourcePath = $"Jellyfin.Plugin.JellyfinEnhanced.js.locales.{sanitizedLang}.json";
            var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(resourcePath);

            if (stream == null && sanitizedLang.Contains('-'))
            {
                // Fall back from regional variant (e.g. de-DE) to the base language (de).
                // Jellyfin reports BCP-47 codes like de-DE when the user picks "Auto" or a
                // regional locale, but the plugin only ships base-language files for most
                // languages. Without this fallback the user gets English instead of German.
                var baseLang = sanitizedLang.Split('-')[0];
                var fallbackPath = $"Jellyfin.Plugin.JellyfinEnhanced.js.locales.{baseLang}.json";
                stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(fallbackPath);
                if (stream != null)
                {
                    _logger.LogInformation($"Locale file not found for {sanitizedLang}, falling back to base language {baseLang}");
                }
            }

            if (stream == null)
            {
                _logger.LogWarning($"Locale file not found for language: {sanitizedLang}");
                return NotFound();
            }

            return new FileStreamResult(stream, "application/json");
        }

        private ActionResult GetScriptResource(string resourcePath)
        {
            var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream($"Jellyfin.Plugin.JellyfinEnhanced.{resourcePath.Replace('/', '.')}");
            if (stream == null) return NotFound();

            // Pick a content type that matches the requested file. Defaults to JS for the
            // legacy /js/* callers; adds CSS so /css/* doesn't get served as application/javascript
            // (which breaks <link rel="stylesheet"> in strict-MIME browsers).
            string contentType = "application/javascript";
            if (resourcePath.EndsWith(".css", StringComparison.OrdinalIgnoreCase))
                contentType = "text/css";
            else if (resourcePath.EndsWith(".json", StringComparison.OrdinalIgnoreCase) || resourcePath.EndsWith(".map", StringComparison.OrdinalIgnoreCase))
                contentType = "application/json";
            else if (resourcePath.EndsWith(".html", StringComparison.OrdinalIgnoreCase))
                contentType = "text/html";

            // DevMode: no-cache so the browser always re-fetches after a server restart,
            // useful when iterating on JS without bumping the version number.
            // Production: the script URL includes ?v={version}-{dllTimestamp}, so the URL
            // changes on every build and immutable caching is safe.
            var devMode = _configProvider.ConfigurationOrNull?.DevMode == true;
            Response.Headers["Cache-Control"] = devMode ? "no-store" : "public, max-age=31536000, immutable";
            return new FileStreamResult(stream, contentType);
        }
    }
}
