using System.Runtime.CompilerServices;
using System.Text.Json;
using Jellyfin.Plugin.JellyfinEnhanced.Configuration;
using Jellyfin.Plugin.JellyfinEnhanced.Services;
using Jellyfin.Plugin.JellyfinEnhanced.Tests.TestDoubles;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;

namespace Jellyfin.Plugin.JellyfinEnhanced.Tests.Configuration
{
    /// <summary>
    /// Byte-exact golden tests for every JSON file the plugin persists to disk
    /// (per-user settings/shortcuts/bookmarks/elsewhere/hidden-content/watchlist,
    /// the shared reviews.json, and maintenance-state.json).
    ///
    /// The goldens were generated by the ORIGINAL Newtonsoft.Json persistence
    /// path (JE_UPDATE_GOLDEN=1) and pin the exact on-disk format:
    ///   - PascalCase property names (no naming policy),
    ///   - 2-space indentation,
    ///   - null values written out (NullValueHandling.Include on write),
    ///   - non-ASCII BMP characters written raw (not \uXXXX-escaped),
    ///   - ISO 8601 dates with trailing-zero trimming ("Z" for UTC, no suffix
    ///     for Unspecified).
    /// The System.Text.Json migration must keep producing these exact bytes so
    /// files written by the new code remain readable by (and diffable against)
    /// files written by every previous plugin version.
    ///
    /// Known deliberate byte-level divergences are NOT covered by these goldens
    /// and are pinned by value-level tests instead (see UserFileReadCompatTests):
    ///   - whole-number doubles: Newtonsoft wrote "1.0", STJ writes "1"
    ///     (both read either form),
    ///   - astral-plane characters (emoji): Newtonsoft wrote them raw, STJ
    ///     escapes them as surrogate pairs (semantically identical JSON),
    ///   - raw client JSON (JsonElement) pass-through: Newtonsoft re-parsed and
    ///     normalized full ISO date strings and exponent numbers; STJ preserves
    ///     the client's text verbatim (both forms read identically).
    ///
    /// If one of these tests fails, fix the serializer options — never the golden.
    /// A deliberate format change must regenerate goldens in its own commit:
    ///   JE_UPDATE_GOLDEN=1 dotnet test --filter UserFileFormatGoldenTests
    /// </summary>
    public class UserFileFormatGoldenTests : IDisposable
    {
        // Canonical dashless-lowercase user id (the store normalizes to this form).
        private const string UserId = "3f2504e04f8941d39a0c0305e82c3301";

        private readonly string _baseDir;
        private readonly UserConfigurationManager _manager;

        public UserFileFormatGoldenTests()
        {
            _baseDir = Path.Combine(Path.GetTempPath(), "je-userfile-golden-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(_baseDir);
            _manager = new UserConfigurationManager(new StubAppPaths(_baseDir), NullLogger<UserConfigurationManager>.Instance);
        }

        public void Dispose()
        {
            try { Directory.Delete(_baseDir, recursive: true); } catch { /* best effort */ }
        }

        private string ConfigBaseDir => Path.Combine(_baseDir, "configurations", "Jellyfin.Plugin.JellyfinEnhanced");
        private string UserFilePath(string fileName) => Path.Combine(ConfigBaseDir, UserId, fileName);

        // ─── Per-user files (UserConfigurationStore.SaveUserConfiguration) ───────

        [Fact]
        public void Settings_Save_MatchesGolden()
        {
            var settings = new UserSettings
            {
                AutoPauseEnabled = true,
                PauseScreenDelaySeconds = 9,
                SelectedStylePresetIndex = 3,
                CustomSubtitleTextColor = "#AABBCCDD",
                UsingCustomColors = true,
                SubtitleVerticalPosition = 42,
                WatchProgressMode = "time",
                WatchProgressTimeFormat = "minutes",
                ShowResolutionTag = false,
                // int? orders: mixed null / non-null so the golden pins that
                // nulls are WRITTEN (NullValueHandling.Include) not omitted.
                ResolutionTagOrder = 2,
                SourceTagOrder = null,
                DynamicRangeTagOrder = 0,
                QualityTagsPosition = "bottom-right",
                // Non-ASCII BMP + escapes: raw é/映画, escaped quote and backslash.
                LastOpenedTab = "élsewhere-映画 \"tab\" c:\\path",
                DisplayLanguage = "français",
                CalendarDisplayMode = "grid",
            };

            _manager.SaveUserConfiguration(UserId, "settings.json", settings);
            AssertMatchesGolden("settings.write", File.ReadAllText(UserFilePath("settings.json")));

            // The lenient read path must round-trip what was just written.
            var back = _manager.GetUserConfiguration<UserSettings>(UserId, "settings.json");
            Assert.True(back.AutoPauseEnabled);
            Assert.Equal(9, back.PauseScreenDelaySeconds);
            Assert.Equal("élsewhere-映画 \"tab\" c:\\path", back.LastOpenedTab);
            Assert.Null(back.SourceTagOrder);
            Assert.Equal(2, back.ResolutionTagOrder);
            Assert.Equal(0, back.DynamicRangeTagOrder);
        }

        [Fact]
        public void Shortcuts_Save_MatchesGolden()
        {
            var shortcuts = new UserShortcuts
            {
                Shortcuts = new List<Shortcut>
                {
                    new Shortcut { Name = "PlayPause", Key = "Space", Label = "Play / Pause", Category = "Playback" },
                    new Shortcut { Name = "Sück", Key = "ü", Label = "Ümlaut-Kürzel", Category = "Größe" },
                },
            };

            _manager.SaveUserConfiguration(UserId, "shortcuts.json", shortcuts);
            AssertMatchesGolden("shortcuts.write", File.ReadAllText(UserFilePath("shortcuts.json")));

            var back = _manager.GetUserConfiguration<UserShortcuts>(UserId, "shortcuts.json");
            Assert.Equal(2, back.Shortcuts.Count);
            Assert.Equal("Ümlaut-Kürzel", back.Shortcuts[1].Label);
        }

        [Fact]
        public void Bookmark_Save_MatchesGolden()
        {
            var bookmarks = new UserBookmark
            {
                Bookmarks = new Dictionary<string, BookmarkItem>
                {
                    // Fractional timestamps only: whole-number doubles are a known
                    // byte-level divergence (Newtonsoft "1.0" vs STJ "1") pinned by
                    // a value-level test in UserFileReadCompatTests instead.
                    ["item-1:12.25"] = new BookmarkItem
                    {
                        ItemId = "item-1",
                        TmdbId = "603",
                        MediaType = "movie",
                        Name = "Amélie — 映画",
                        Timestamp = 12.25,
                        Label = "Café scene ☕", // U+2615 is BMP: raw in both stacks
                        CreatedAt = "2024-01-15T10:30:00.000Z",
                        UpdatedAt = "2024-01-16T11:31:01.500Z",
                        SyncedFrom = "",
                    },
                    ["item-2:99.5"] = new BookmarkItem
                    {
                        ItemId = "item-2",
                        MediaType = "tv",
                        Name = "Plain",
                        Timestamp = 99.5,
                    },
                },
            };

            _manager.SaveUserConfiguration(UserId, "bookmark.json", bookmarks);
            AssertMatchesGolden("bookmark.write", File.ReadAllText(UserFilePath("bookmark.json")));

            var back = _manager.GetUserConfiguration<UserBookmark>(UserId, "bookmark.json");
            Assert.Equal(12.25, back.Bookmarks["item-1:12.25"].Timestamp);
            Assert.Equal("Amélie — 映画", back.Bookmarks["item-1:12.25"].Name);
            // String CreatedAt must come back verbatim (not date-normalized).
            Assert.Equal("2024-01-15T10:30:00.000Z", back.Bookmarks["item-1:12.25"].CreatedAt);
        }

        [Fact]
        public void Elsewhere_Save_MatchesGolden()
        {
            var elsewhere = new ElsewhereSettings
            {
                Region = "DE",
                Regions = new List<string> { "DE", "FR", "US" },
                Services = new List<string> { "Netflix", "Crunchyroll" },
            };

            _manager.SaveUserConfiguration(UserId, "elsewhere.json", elsewhere);
            AssertMatchesGolden("elsewhere.write", File.ReadAllText(UserFilePath("elsewhere.json")));
        }

        [Fact]
        public void HiddenContent_Save_MatchesGolden()
        {
            var hidden = new UserHiddenContent
            {
                Items = new Dictionary<string, HiddenContentItem>
                {
                    ["movie-27205"] = new HiddenContentItem
                    {
                        ItemId = "27205",
                        Name = "Inception",
                        Type = "Movie",
                        TmdbId = "27205",
                        HiddenAt = "2024-06-01T08:00:00.000Z",
                        PosterPath = "/poster.jpg",
                        HideScope = "global",
                        // SeasonNumber/EpisodeNumber stay null: golden pins that
                        // nullable ints are written as null, not omitted.
                    },
                    ["episode-42"] = new HiddenContentItem
                    {
                        ItemId = "42",
                        Name = "Épisode spécial",
                        Type = "Episode",
                        SeriesId = "7",
                        SeriesName = "Série télé",
                        SeasonNumber = 2,
                        EpisodeNumber = 5,
                        HideScope = "series",
                    },
                },
                Settings = new HiddenContentSettings
                {
                    FilterSearch = true,
                    ShowButtonLibrary = true,
                    ShowHideConfirmation = false,
                },
            };

            _manager.SaveUserConfiguration(UserId, "hidden-content.json", hidden);
            AssertMatchesGolden("hidden-content.write", File.ReadAllText(UserFilePath("hidden-content.json")));

            var back = _manager.GetUserConfiguration<UserHiddenContent>(UserId, "hidden-content.json");
            Assert.Null(back.Items["movie-27205"].SeasonNumber);
            Assert.Equal(2, back.Items["episode-42"].SeasonNumber);
            Assert.True(back.Settings.FilterSearch);
            Assert.False(back.Settings.ShowHideConfirmation);
        }

        [Fact]
        public void ProcessedWatchlist_Save_MatchesGolden()
        {
            var items = new ProcessedWatchlistItems
            {
                Items = new List<ProcessedWatchlistItem>
                {
                    // Whole-second UTC: serialized without fractional digits ("...:05Z").
                    new ProcessedWatchlistItem
                    {
                        TmdbId = 100,
                        MediaType = "movie",
                        ProcessedAt = new DateTime(2025, 1, 2, 3, 4, 5, DateTimeKind.Utc),
                        Source = "sync",
                    },
                    // Millisecond UTC: three fractional digits survive, trailing zeros trimmed.
                    new ProcessedWatchlistItem
                    {
                        TmdbId = 200,
                        MediaType = "tv",
                        ProcessedAt = new DateTime(2025, 1, 2, 3, 4, 5, 123, DateTimeKind.Utc),
                        Source = "monitor",
                    },
                    // Full 7-digit tick precision UTC.
                    new ProcessedWatchlistItem
                    {
                        TmdbId = 300,
                        MediaType = "movie",
                        ProcessedAt = new DateTime(638712345678912345L, DateTimeKind.Utc),
                        Source = "existing",
                    },
                    // Unspecified kind: no timezone suffix on disk.
                    new ProcessedWatchlistItem
                    {
                        TmdbId = 400,
                        MediaType = "tv",
                        ProcessedAt = new DateTime(2025, 6, 7, 8, 9, 10, DateTimeKind.Unspecified),
                        Source = "sync",
                    },
                },
            };

            _manager.SaveProcessedWatchlistItems(Guid.Parse(UserId), items);
            AssertMatchesGolden("processed-watchlist.write", File.ReadAllText(UserFilePath("processed-watchlist-items.json")));

            var back = _manager.GetProcessedWatchlistItems(Guid.Parse(UserId));
            Assert.Equal(new DateTime(2025, 1, 2, 3, 4, 5, DateTimeKind.Utc), back.Items[0].ProcessedAt);
            Assert.Equal(DateTimeKind.Utc, back.Items[0].ProcessedAt.Kind);
            Assert.Equal(new DateTime(2025, 1, 2, 3, 4, 5, 123, DateTimeKind.Utc), back.Items[1].ProcessedAt);
            Assert.Equal(638712345678912345L, back.Items[2].ProcessedAt.Ticks);
            Assert.Equal(DateTimeKind.Unspecified, back.Items[3].ProcessedAt.Kind);
        }

        /// <summary>
        /// The raw pass-through path: SaveUserConfiguration(JsonElement) persists
        /// client-supplied JSON. The golden pins camelCase keys, unknown fields,
        /// nested arrays/objects, fractional and whole-decimal numbers, JSON null
        /// and non-ASCII text surviving with 2-space indentation.
        /// (Full ISO datetime strings and exponent numbers are deliberately absent:
        /// Newtonsoft normalized those on re-parse; STJ preserves them verbatim.
        /// Both forms are read-compatible — pinned in UserFileReadCompatTests.)
        /// </summary>
        [Fact]
        public void RawClientJson_Save_MatchesGolden()
        {
            const string clientPayload = /*lang=json*/ """
                {
                    "autoPauseEnabled": true,
                    "pauseScreenDelaySeconds": 7,
                    "customLabel": "Amélie — 映画",
                    "someRatio": 0.75,
                    "wholeDecimal": 5.0,
                    "releaseDay": "2024-05-01",
                    "unknownExtra": { "nested": [1, 2.5, null, "drei"] },
                    "nullField": null
                }
                """;

            using var doc = JsonDocument.Parse(clientPayload);
            _manager.SaveUserConfiguration(UserId, "settings.json", doc.RootElement.Clone());

            AssertMatchesGolden("raw-client-settings.write", File.ReadAllText(UserFilePath("settings.json")));
        }

        // ─── Shared reviews.json (ReviewsStore) ─────────────────────────────────

        [Fact]
        public void Reviews_Upsert_MatchesGolden()
        {
            var userIdN = UserId;
            _manager.UpsertReview(userIdN, "movie", "603",
                "Sehr schön — großartig! 映画は最高", rating: null, nowIso: "2024-03-04T05:06:07.000Z");
            _manager.UpsertReview(userIdN, "tv", "1399",
                "Plain \"quoted\" content", rating: 4, nowIso: "2024-03-05T06:07:08.000Z");
            // Second upsert on the same key exercises the update branch (UpdatedAt moves).
            _manager.UpsertReview(userIdN, "tv", "1399",
                "Plain \"quoted\" content v2", rating: 5, nowIso: "2024-03-06T07:08:09.000Z");

            AssertMatchesGolden("reviews.write", File.ReadAllText(Path.Combine(ConfigBaseDir, "reviews.json")));

            var store = _manager.GetAllReviews();
            Assert.Equal(2, store.Reviews.Count);
            var movie = store.Reviews[$"{userIdN}:movie:603"];
            Assert.Null(movie.Rating);
            Assert.Equal("Sehr schön — großartig! 映画は最高", movie.Content);
            var tv = store.Reviews[$"{userIdN}:tv:1399"];
            Assert.Equal(5, tv.Rating);
            Assert.Equal("2024-03-05T06:07:08.000Z", tv.CreatedAt); // preserved from first upsert
            Assert.Equal("2024-03-06T07:08:09.000Z", tv.UpdatedAt);
        }

        // ─── maintenance-state.json (MaintenanceModeService) ─────────────────────

        [Fact]
        public async Task MaintenanceState_ReadSeed_And_UpdateWrite_MatchesGolden()
        {
            // Seed with the committed READ fixture (hand-written, Newtonsoft-era shape).
            var stateDir = Path.Combine(_baseDir, "configurations", "Jellyfin.Plugin.JellyfinEnhanced");
            Directory.CreateDirectory(stateDir);
            File.Copy(FixturePath("maintenance-state.read.active"), Path.Combine(stateDir, "maintenance-state.json"));

            // IUserManager is only touched when users are (re)enabled/disabled; the
            // already-active update path below never dereferences it.
            var service = new MaintenanceModeService(null!, new StubAppPaths(_baseDir), NullLogger<MaintenanceModeService>.Instance);

            var status = service.GetStatus();
            Assert.True(status.IsActive);
            Assert.Equal("Ursprüngliche Wartung", status.Message);
            Assert.Equal("both", status.Action);
            Assert.Equal(new DateTime(2025, 3, 4, 5, 6, 7, DateTimeKind.Utc), status.StartedAt);
            Assert.Null(status.EndsAt);
            Assert.Equal(new[] { "3f2504e04f8941d39a0c0305e82c3301" }, status.AccountDisabledUserIds);
            Assert.Empty(status.RemoteDisabledUserIds);

            // Already-active branch: updates Message/EndsAt in place and rewrites the file.
            await service.EnableAsync("Wartung aktualisiert — 更新", durationMinutes: 0, action: "both", affectedUserIds: null);

            AssertMatchesGolden("maintenance-state.write.updated", File.ReadAllText(Path.Combine(stateDir, "maintenance-state.json")));
        }

        // ─── Golden plumbing ─────────────────────────────────────────────────────

        private static void AssertMatchesGolden(string name, string actual)
        {
            if (Environment.GetEnvironmentVariable("JE_UPDATE_GOLDEN") == "1")
            {
                Directory.CreateDirectory(SourceFixtureDirectory());
                File.WriteAllText(Path.Combine(SourceFixtureDirectory(), name + ".json"), actual);
                return;
            }

            var goldenPath = FixturePath(name);
            Assert.True(
                File.Exists(goldenPath),
                $"Missing golden {name}.json. Run once with JE_UPDATE_GOLDEN=1 to generate it, review, and commit.");

            // Normalize CRLF so goldens generated on Linux also compare on Windows
            // (both JSON stacks use Environment.NewLine for indented output).
            var expected = File.ReadAllText(goldenPath).Replace("\r\n", "\n");
            Assert.Equal(expected, actual.Replace("\r\n", "\n"));
        }

        internal static string FixturePath(string name)
            => Path.Combine(AppContext.BaseDirectory, "Snapshots", "UserFiles", name + ".json");

        private static string SourceFixtureDirectory([CallerFilePath] string sourceFile = "")
            => Path.GetFullPath(Path.Combine(Path.GetDirectoryName(sourceFile)!, "..", "Snapshots", "UserFiles"));
    }
}
